apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devops-control-center.fullname" . }}-config
  labels:
    {{- include "devops-control-center.labels" . | nindent 4 }}
data:
  ENVIRONMENT: {{ .Values.global.environment | quote }}
  PROJECT_NAME: {{ .Values.backend.env.PROJECT_NAME | quote }}
  LOG_LEVEL: {{ .Values.backend.env.LOG_LEVEL | quote }}
  ACCESS_TOKEN_EXPIRE_MINUTES: {{ .Values.backend.env.ACCESS_TOKEN_EXPIRE_MINUTES | quote }}
  POSTGRES_SERVER: "{{ include "devops-control-center.fullname" . }}-postgres-svc"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: {{ .Values.postgresql.auth.database | quote }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devops-control-center.fullname" . }}-secrets
  labels:
    {{- include "devops-control-center.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: "supersecret-jwt-signing-key-devops-control-center"
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.postgresPassword | quote }}
  GITHUB_PAT: "ghp_mock_production_token_12345"
  JENKINS_TOKEN: "11a_mock_production_token_12345"
